# action modules will be called subsequentially
actions: ["predict"]

scrap:
  gov_price: 
    url: "https://onemotoring.lta.gov.sg/content/onemotoring/home/buying/upfront-vehicle-costs/open-market-value--omv-.html"
    save_path: "./data/gov_price.csv"
    year_range: [2002, 2022]
preprocess:
  # preprocess data
  train: # file name under preprocess module
    # procedure will be like: update -> add -> drop
    
    # if path is not specified, then directly find correspond csv under ./data
    # path: "./data/train.csv"

    # if column name is not specified, then get its name as default
    reg_date: "reg_date_customized"
          
    _add: []
    
    # column name of the column to be deleted
    _drop: ["listing_id","title","description","fuel_type","opc_scheme","lifespan","eco_category","features","accessories","indicative_price"]
    
    save_path: "./data/train_processed.csv"
  test:
    save_path: "./data/test_processed.csv"
  gov_price: 
    save_path: "./data/gov_price_processed.csv"
predict:
  dataset: "SimpleDataset"

  SimpleDataset:
    path: './data/train_processed.csv'
    test_path: './data/test_processed.csv' # comment this line to make train-val split on trian set

  model: "LogisticRegressionModel"

  LogisticRegressionModel:
    C: 1.0
    max_iter: 500

  metric: "MSE"
  dump_path: './data/predict.csv'